### ISSUE TITLE
Error when converting

### ISSUE THREAD

**Issue by lepmik** [CINPLA/expipe-plugin-cinpla#66]
```python
*******************************
Processing action 1849-220319-3
*******************************

>>> Re-copying action 1849-220319-3 to new project


>>> Converting to NWB

Source data is valid!
Attaching probe
/fp/projects01/ec109/software/expipe-plugin-cinpla/src/expipe_plugin_cinpla/scripts/register.py:49: UserWarning: Species not found in entity attributes, using default Rattus norvegicus
  warnings.warn("Species not found in entity attributes, using default Rattus norvegicus")
/fp/projects01/ec109/software/expipe-plugin-cinpla/src/expipe_plugin_cinpla/scripts/register.py:55: UserWarning: Sex not found in entity attributes, using default M
  warnings.warn("Sex not found in entity attributes, using default M")
Running conversion to NWB
Metadata is valid!
conversion_options is valid!
NWB file saved at /projects/ec109/Mikkel/septum-mec-new/actions/1849-220319-3/data/main.nwb!

>>> Running processing


Preprocessing recording:
        Num channels: 32
        Duration: 841.97 s
        Active channels: 32

Writing to NWB
        Adding LFP
Cleaning up
        Saved to NWB:  /projects/ec109/Mikkel/septum-mec-new/actions/1849-220319-3/data/main.nwb
Total processing time: 47.0s

>>> Copying Phy folders

        Copying folder for kilosort2

>>> Applying Phy curation and set main units

Loaded Phy-curated sorting for kilosort2:
UnitsSelectionSorting: 13 units - 1 segments - 30.0kHz
Could not load raw sorting for kilosort2. Using None: processing/ecephys/RawUnits-kilosort2 not found in the NWB file!Available options are: [].
Error processing action 1849-220319-3. Removing it from new project:
Error:
The sorting object has spikes exceeding the recording duration. You have to remove those spikes with the `spikeinterface.curation.remove_excess_spikes()` function
```

**Comment by lepmik** [comment]
Full log

```
Continuing from existing /projects/ec109/Mikkel/septum-mec-new
/fp/homes01/u01/ec-bjornmik/.local/lib/python3.11/site-packages/expipe/core.py:700: UserWarning: Requested project with name 'septum-mec-new', but found 'septum-mec-new-new'
  warnings.warn(
Found 121 actions in septum-mec

Actions that need conversion: 92
Actions that will be converted: 92

*******************************
Processing action 1839-200619-1
*******************************

NWB file already exists for action 1839-200619-1
Spikeinterface folder already exists for action 1839-200619-1
Action 1839-200619-1 done in 0.03 s

*******************************
Processing action 1834-060319-4
*******************************

NWB file already exists for action 1834-060319-4
Spikeinterface folder already exists for action 1834-060319-4
Action 1834-060319-4 done in 0.01 s

*******************************
Processing action 1839-120619-2
*******************************

NWB file already exists for action 1839-120619-2
Spikeinterface folder already exists for action 1839-120619-2
Action 1839-120619-2 done in 0.00 s

*******************************
Processing action 1833-260619-4
*******************************

NWB file already exists for action 1833-260619-4
Spikeinterface folder already exists for action 1833-260619-4
Action 1833-260619-4 done in 0.05 s

*******************************
Processing action 1833-020719-3
*******************************

NWB file already exists for action 1833-020719-3
Spikeinterface folder already exists for action 1833-020719-3
Action 1833-020719-3 done in 0.03 s

*******************************
Processing action 1834-120319-2
*******************************

NWB file already exists for action 1834-120319-2
Spikeinterface folder already exists for action 1834-120319-2
Action 1834-120319-2 done in 0.01 s

*******************************
Processing action 1839-120619-4
*******************************

NWB file already exists for action 1839-120619-4
Spikeinterface folder already exists for action 1839-120619-4
Action 1839-120619-4 done in 0.02 s

*******************************
Processing action 1849-060319-4
*******************************

NWB file already exists for action 1849-060319-4
Spikeinterface folder already exists for action 1849-060319-4
Action 1849-060319-4 done in 0.01 s

*******************************
Processing action 1833-120619-4
*******************************

NWB file already exists for action 1833-120619-4
Spikeinterface folder already exists for action 1833-120619-4
Action 1833-120619-4 done in 0.00 s

*******************************
Processing action 1834-010319-1
*******************************

NWB file already exists for action 1834-010319-1
Spikeinterface folder already exists for action 1834-010319-1
Action 1834-010319-1 done in 0.00 s

*******************************
Processing action 1833-060619-1
*******************************

>>> Re-copying action 1833-060619-1 to new project


>>> Converting to NWB

Source data is valid!
Attaching probe
Running conversion to NWB
Metadata is valid!
conversion_options is valid!
NWB file saved at /projects/ec109/Mikkel/septum-mec-new/actions/1833-060619-1/data/main.nwb!
Error processing action 1833-060619-1. Removing it from new project:
Error:



*******************************
Processing action 1834-110319-6
*******************************

NWB file already exists for action 1834-110319-6
Spikeinterface folder already exists for action 1834-110319-6
Action 1834-110319-6 done in 0.01 s

*******************************
Processing action 1849-150319-1
*******************************

NWB file already exists for action 1849-150319-1
Spikeinterface folder already exists for action 1849-150319-1
Action 1849-150319-1 done in 0.02 s

*******************************
Processing action 1839-290519-2
*******************************

NWB file already exists for action 1839-290519-2
Spikeinterface folder already exists for action 1839-290519-2
Action 1839-290519-2 done in 0.00 s

*******************************
Processing action 1839-290519-3
*******************************

NWB file already exists for action 1839-290519-3
Spikeinterface folder already exists for action 1839-290519-3
Action 1839-290519-3 done in 0.01 s

*******************************
Processing action 1833-120619-1
*******************************

NWB file already exists for action 1833-120619-1
Spikeinterface folder already exists for action 1833-120619-1
Action 1833-120619-1 done in 0.00 s

*******************************
Processing action 1834-230219-1
*******************************

NWB file already exists for action 1834-230219-1
Spikeinterface folder already exists for action 1834-230219-1
Action 1834-230219-1 done in 0.01 s

*******************************
Processing action 1849-110319-3
*******************************

NWB file already exists for action 1849-110319-3
Spikeinterface folder already exists for action 1849-110319-3
Action 1849-110319-3 done in 0.00 s

*******************************
Processing action 1849-110319-2
*******************************

NWB file already exists for action 1849-110319-2
Spikeinterface folder already exists for action 1849-110319-2
Action 1849-110319-2 done in 0.00 s

*******************************
Processing action 1833-010719-1
*******************************

NWB file already exists for action 1833-010719-1
Spikeinterface folder already exists for action 1833-010719-1
Action 1833-010719-1 done in 0.01 s

*******************************
Processing action 1833-050619-2
*******************************

NWB file already exists for action 1833-050619-2
Spikeinterface folder already exists for action 1833-050619-2
Action 1833-050619-2 done in 0.02 s

*******************************
Processing action 1839-060619-5
*******************************

NWB file already exists for action 1839-060619-5
Spikeinterface folder already exists for action 1839-060619-5
Action 1839-060619-5 done in 0.01 s

*******************************
Processing action 1833-200619-2
*******************************

NWB file already exists for action 1833-200619-2
Spikeinterface folder already exists for action 1833-200619-2
Action 1833-200619-2 done in 0.00 s

*******************************
Processing action 1849-280219-2
*******************************

NWB file already exists for action 1849-280219-2
Spikeinterface folder already exists for action 1849-280219-2
Action 1849-280219-2 done in 0.01 s

*******************************
Processing action 1833-020719-4
*******************************

NWB file already exists for action 1833-020719-4
Spikeinterface folder already exists for action 1833-020719-4
Action 1833-020719-4 done in 0.00 s

*******************************
Processing action 1833-010719-2
*******************************

NWB file already exists for action 1833-010719-2
Spikeinterface folder already exists for action 1833-010719-2
Action 1833-010719-2 done in 0.03 s

*******************************
Processing action 1839-290519-1
*******************************

NWB file already exists for action 1839-290519-1
Spikeinterface folder already exists for action 1839-290519-1
Action 1839-290519-1 done in 0.00 s

*******************************
Processing action 1849-010319-5
*******************************

NWB file already exists for action 1849-010319-5
Spikeinterface folder already exists for action 1849-010319-5
Action 1849-010319-5 done in 0.01 s

*******************************
Processing action 1834-120319-1
*******************************

NWB file already exists for action 1834-120319-1
Spikeinterface folder already exists for action 1834-120319-1
Action 1834-120319-1 done in 0.00 s

*******************************
Processing action 1834-060319-3
*******************************

NWB file already exists for action 1834-060319-3
Spikeinterface folder already exists for action 1834-060319-3
Action 1834-060319-3 done in 0.01 s

*******************************
Processing action 1834-220319-4
*******************************

NWB file already exists for action 1834-220319-4
Spikeinterface folder already exists for action 1834-220319-4
Action 1834-220319-4 done in 0.01 s

*******************************
Processing action 1833-290519-3
*******************************

NWB file already exists for action 1833-290519-3
Spikeinterface folder already exists for action 1833-290519-3
Action 1833-290519-3 done in 0.01 s

*******************************
Processing action 1833-260619-1
*******************************

NWB file already exists for action 1833-260619-1
Spikeinterface folder already exists for action 1833-260619-1
Action 1833-260619-1 done in 0.00 s

*******************************
Processing action 1849-220319-3
*******************************

>>> Re-copying action 1849-220319-3 to new project


>>> Converting to NWB

Source data is valid!
Attaching probe
/fp/projects01/ec109/software/expipe-plugin-cinpla/src/expipe_plugin_cinpla/scripts/register.py:49: UserWarning: Species not found in entity attributes, using default Rattus norvegicus
  warnings.warn("Species not found in entity attributes, using default Rattus norvegicus")
/fp/projects01/ec109/software/expipe-plugin-cinpla/src/expipe_plugin_cinpla/scripts/register.py:55: UserWarning: Sex not found in entity attributes, using default M
  warnings.warn("Sex not found in entity attributes, using default M")
Running conversion to NWB
Metadata is valid!
conversion_options is valid!
NWB file saved at /projects/ec109/Mikkel/septum-mec-new/actions/1849-220319-3/data/main.nwb!

>>> Running processing


Preprocessing recording:
        Num channels: 32
        Duration: 841.97 s
        Active channels: 32

Writing to NWB
        Adding LFP
Cleaning up
        Saved to NWB:  /projects/ec109/Mikkel/septum-mec-new/actions/1849-220319-3/data/main.nwb
Total processing time: 47.0s

>>> Copying Phy folders

        Copying folder for kilosort2

>>> Applying Phy curation and set main units

Loaded Phy-curated sorting for kilosort2:
UnitsSelectionSorting: 13 units - 1 segments - 30.0kHz
Could not load raw sorting for kilosort2. Using None: processing/ecephys/RawUnits-kilosort2 not found in the NWB file!Available options are: [].
Error processing action 1849-220319-3. Removing it from new project:
Error:
The sorting object has spikes exceeding the recording duration. You have to remove those spikes with the `spikeinterface.curation.remove_excess_spikes()` function


*******************************
Processing action 1849-110319-1
*******************************

NWB file already exists for action 1849-110319-1
Spikeinterface folder already exists for action 1849-110319-1
Action 1849-110319-1 done in 0.02 s

*******************************
Processing action 1849-220319-2
*******************************

NWB file already exists for action 1849-220319-2
Spikeinterface folder already exists for action 1849-220319-2
Action 1849-220319-2 done in 0.03 s

*******************************
Processing action 1833-120619-3
*******************************

>>> Re-copying action 1833-120619-3 to new project


>>> Converting to NWB

Source data is valid!
Attaching probe
Running conversion to NWB
Metadata is valid!
conversion_options is valid!
NWB file saved at /projects/ec109/Mikkel/septum-mec-new/actions/1833-120619-3/data/main.nwb!

>>> Running processing


Preprocessing recording:
        Num channels: 32
        Duration: 804.05 s
        Active channels: 32

Writing to NWB
        Adding LFP
Cleaning up
        Saved to NWB:  /projects/ec109/Mikkel/septum-mec-new/actions/1833-120619-3/data/main.nwb
Total processing time: 45.0s

>>> Copying Phy folders

        Copying folder for kilosort2

>>> Applying Phy curation and set main units

Loaded Phy-curated sorting for kilosort2:
UnitsSelectionSorting: 13 units - 1 segments - 30.0kHz
Could not load raw sorting for kilosort2. Using None: processing/ecephys/RawUnits-kilosort2 not found in the NWB file!Available options are: [].
Error processing action 1833-120619-3. Removing it from new project:
Error:
The sorting object has spikes exceeding the recording duration. You have to remove those spikes with the `spikeinterface.curation.remove_excess_spikes()` function


*******************************
Processing action 1839-060619-3
*******************************

NWB file already exists for action 1839-060619-3
Spikeinterface folder already exists for action 1839-060619-3
Action 1839-060619-3 done in 0.03 s

*******************************
Processing action 1849-220319-4
*******************************

NWB file already exists for action 1849-220319-4
Spikeinterface folder already exists for action 1849-220319-4
Action 1849-220319-4 done in 0.02 s

*******************************
Processing action 1833-290519-1
*******************************

NWB file already exists for action 1833-290519-1
Spikeinterface folder already exists for action 1833-290519-1
Action 1833-290519-1 done in 0.01 s

*******************************
Processing action 1849-060319-1
*******************************

NWB file already exists for action 1849-060319-1
Spikeinterface folder already exists for action 1849-060319-1
Action 1849-060319-1 done in 0.02 s

*******************************
Processing action 1834-120319-4
*******************************

NWB file already exists for action 1834-120319-4
Spikeinterface folder already exists for action 1834-120319-4
Action 1834-120319-4 done in 0.02 s

*******************************
Processing action 1833-290519-2
*******************************

>>> Re-copying action 1833-290519-2 to new project


>>> Converting to NWB

Source data is valid!
Attaching probe
Running conversion to NWB
Metadata is valid!
conversion_options is valid!
NWB file saved at /projects/ec109/Mikkel/septum-mec-new/actions/1833-290519-2/data/main.nwb!

>>> Running processing


Preprocessing recording:
        Num channels: 32
        Duration: 902.6 s
        Active channels: 32

Writing to NWB
        Adding LFP
Cleaning up
        Saved to NWB:  /projects/ec109/Mikkel/septum-mec-new/actions/1833-290519-2/data/main.nwb
Total processing time: 50.0s

>>> Copying Phy folders

        Copying folder for kilosort2

>>> Applying Phy curation and set main units

Loaded Phy-curated sorting for kilosort2:
UnitsSelectionSorting: 21 units - 1 segments - 30.0kHz
Could not load raw sorting for kilosort2. Using None: processing/ecephys/RawUnits-kilosort2 not found in the NWB file!Available options are: [].
Error processing action 1833-290519-2. Removing it from new project:
Error:
The sorting object has spikes exceeding the recording duration. You have to remove those spikes with the `spikeinterface.curation.remove_excess_spikes()` function


*******************************
Processing action 1849-150319-4
*******************************

NWB file already exists for action 1849-150319-4
Spikeinterface folder already exists for action 1849-150319-4
Action 1849-150319-4 done in 0.06 s

*******************************
Processing action 1834-220319-3
*******************************

>>> Re-copying action 1834-220319-3 to new project


>>> Converting to NWB

Source data is valid!
Error processing action 1834-220319-3. Removing it from new project:
Error:
This dataset is multi-block. Spikeinterface can load one block at a time. Use 'block_index' to select the block to be loaded.


*******************************
Processing action 1839-060619-1
*******************************

NWB file already exists for action 1839-060619-1
Spikeinterface folder already exists for action 1839-060619-1
Action 1839-060619-1 done in 0.03 s

*******************************
Processing action 1849-260219-2
*******************************

NWB file already exists for action 1849-260219-2
Spikeinterface folder already exists for action 1849-260219-2
Action 1849-260219-2 done in 0.03 s

*******************************
Processing action 1839-120619-1
*******************************

NWB file already exists for action 1839-120619-1
Spikeinterface folder already exists for action 1839-120619-1
Action 1839-120619-1 done in 0.04 s

*******************************
Processing action 1833-050619-1
*******************************

>>> Re-copying action 1833-050619-1 to new project


>>> Converting to NWB

Source data is valid!
Attaching probe
Running conversion to NWB
Metadata is valid!
conversion_options is valid!
NWB file saved at /projects/ec109/Mikkel/septum-mec-new/actions/1833-050619-1/data/main.nwb!

>>> Running processing


Preprocessing recording:
        Num channels: 32
        Duration: 1200.76 s
        Active channels: 32

Writing to NWB
        Adding LFP
Cleaning up
        Saved to NWB:  /projects/ec109/Mikkel/septum-mec-new/actions/1833-050619-1/data/main.nwb
Total processing time: 66.0s

>>> Copying Phy folders

        Copying folder for kilosort2

>>> Applying Phy curation and set main units

Loaded Phy-curated sorting for kilosort2:
UnitsSelectionSorting: 9 units - 1 segments - 30.0kHz
Could not load raw sorting for kilosort2. Using None: processing/ecephys/RawUnits-kilosort2 not found in the NWB file!Available options are: [].
Error processing action 1833-050619-1. Removing it from new project:
Error:
The sorting object has spikes exceeding the recording duration. You have to remove those spikes with the `spikeinterface.curation.remove_excess_spikes()` function


*******************************
Processing action 1849-280219-3
*******************************

NWB file already exists for action 1849-280219-3
Spikeinterface folder already exists for action 1849-280219-3
Action 1849-280219-3 done in 0.03 s

*******************************
Processing action 1833-020719-1
*******************************

NWB file already exists for action 1833-020719-1
Spikeinterface folder already exists for action 1833-020719-1
Action 1833-020719-1 done in 0.02 s

*******************************
Processing action 1834-150319-2
*******************************

NWB file already exists for action 1834-150319-2
Spikeinterface folder already exists for action 1834-150319-2
Action 1834-150319-2 done in 0.06 s

*******************************
Processing action 1834-220319-2
*******************************

NWB file already exists for action 1834-220319-2
Spikeinterface folder already exists for action 1834-220319-2
Action 1834-220319-2 done in 0.02 s

*******************************
Processing action 1833-050619-4
*******************************

NWB file already exists for action 1833-050619-4
Spikeinterface folder already exists for action 1833-050619-4
Action 1833-050619-4 done in 0.02 s

*******************************
Processing action 1849-220319-5
*******************************

NWB file already exists for action 1849-220319-5
Spikeinterface folder already exists for action 1849-220319-5
Action 1849-220319-5 done in 0.01 s

*******************************
Processing action 1839-060619-4
*******************************

NWB file already exists for action 1839-060619-4
Spikeinterface folder already exists for action 1839-060619-4
Action 1839-060619-4 done in 0.02 s

*******************************
Processing action 1849-010319-2
*******************************

NWB file already exists for action 1849-010319-2
Spikeinterface folder already exists for action 1849-010319-2
Action 1849-010319-2 done in 0.01 s

*******************************
Processing action 1849-280219-4
*******************************

NWB file already exists for action 1849-280219-4
Spikeinterface folder already exists for action 1849-280219-4
Action 1849-280219-4 done in 0.01 s

*******************************
Processing action 1834-110319-1
*******************************

NWB file already exists for action 1834-110319-1
Spikeinterface folder already exists for action 1834-110319-1
Action 1834-110319-1 done in 0.01 s

*******************************
Processing action 1834-150319-3
*******************************

NWB file already exists for action 1834-150319-3
Spikeinterface folder already exists for action 1834-150319-3
Action 1834-150319-3 done in 0.01 s

*******************************
Processing action 1834-150319-4
*******************************

NWB file already exists for action 1834-150319-4
Spikeinterface folder already exists for action 1834-150319-4
Action 1834-150319-4 done in 0.01 s

*******************************
Processing action 1834-010319-5
*******************************

NWB file already exists for action 1834-010319-5
Spikeinterface folder already exists for action 1834-010319-5
Action 1834-010319-5 done in 0.01 s

*******************************
Processing action 1849-150319-2
*******************************

>>> Re-copying action 1849-150319-2 to new project


>>> Converting to NWB

Source data is valid!
Attaching probe
Running conversion to NWB
Metadata is valid!
conversion_options is valid!
NWB file saved at /projects/ec109/Mikkel/septum-mec-new/actions/1849-150319-2/data/main.nwb!

>>> Running processing


Preprocessing recording:
        Num channels: 32
        Duration: 890.83 s
        Active channels: 32

Writing to NWB
        Adding LFP
Cleaning up
        Saved to NWB:  /projects/ec109/Mikkel/septum-mec-new/actions/1849-150319-2/data/main.nwb
Total processing time: 50.0s

>>> Copying Phy folders

        Copying folder for kilosort2

>>> Applying Phy curation and set main units

Loaded Phy-curated sorting for kilosort2:
UnitsSelectionSorting: 17 units - 1 segments - 30.0kHz
Could not load raw sorting for kilosort2. Using None: processing/ecephys/RawUnits-kilosort2 not found in the NWB file!Available options are: [].
Error processing action 1849-150319-2. Removing it from new project:
Error:
The sorting object has spikes exceeding the recording duration. You have to remove those spikes with the `spikeinterface.curation.remove_excess_spikes()` function


*******************************
Processing action 1834-150319-1
*******************************

NWB file already exists for action 1834-150319-1
Spikeinterface folder already exists for action 1834-150319-1
Action 1834-150319-1 done in 0.01 s

*******************************
Processing action 1849-150319-3
*******************************

NWB file already exists for action 1849-150319-3
Spikeinterface folder already exists for action 1849-150319-3
Action 1849-150319-3 done in 0.02 s

*******************************
Processing action 1833-200619-1
*******************************

NWB file already exists for action 1833-200619-1
Spikeinterface folder already exists for action 1833-200619-1
Action 1833-200619-1 done in 0.01 s

*******************************
Processing action 1833-050619-3
*******************************

NWB file already exists for action 1833-050619-3
Spikeinterface folder already exists for action 1833-050619-3
Action 1833-050619-3 done in 0.03 s

*******************************
Processing action 1834-250219-1
*******************************

NWB file already exists for action 1834-250219-1
Spikeinterface folder already exists for action 1834-250219-1
Action 1834-250219-1 done in 0.03 s

*******************************
Processing action 1833-020719-2
*******************************

>>> Re-copying action 1833-020719-2 to new project


>>> Converting to NWB

Source data is valid!
Attaching probe
Running conversion to NWB
Metadata is valid!
conversion_options is valid!
NWB file saved at /projects/ec109/Mikkel/septum-mec-new/actions/1833-020719-2/data/main.nwb!

>>> Running processing


Preprocessing recording:
        Num channels: 32
        Duration: 752.83 s
        Active channels: 32

Writing to NWB
        Adding LFP
Cleaning up
        Saved to NWB:  /projects/ec109/Mikkel/septum-mec-new/actions/1833-020719-2/data/main.nwb
Total processing time: 42.0s

>>> Copying Phy folders

        Copying folder for kilosort2

>>> Applying Phy curation and set main units

Loaded Phy-curated sorting for kilosort2:
UnitsSelectionSorting: 21 units - 1 segments - 30.0kHz
Could not load raw sorting for kilosort2. Using None: processing/ecephys/RawUnits-kilosort2 not found in the NWB file!Available options are: [].
Error processing action 1833-020719-2. Removing it from new project:
Error:
The sorting object has spikes exceeding the recording duration. You have to remove those spikes with the `spikeinterface.curation.remove_excess_spikes()` function


*******************************
Processing action 1849-010319-4
*******************************

NWB file already exists for action 1849-010319-4
Spikeinterface folder already exists for action 1849-010319-4
Action 1849-010319-4 done in 0.02 s

*******************************
Processing action 1834-060319-1
*******************************

NWB file already exists for action 1834-060319-1
Spikeinterface folder already exists for action 1834-060319-1
Action 1834-060319-1 done in 0.03 s

*******************************
Processing action 1834-060319-2
*******************************

NWB file already exists for action 1834-060319-2
Spikeinterface folder already exists for action 1834-060319-2
Action 1834-060319-2 done in 0.02 s

*******************************
Processing action 1834-220319-1
*******************************

NWB file already exists for action 1834-220319-1
Spikeinterface folder already exists for action 1834-220319-1
Action 1834-220319-1 done in 0.03 s

*******************************
Processing action 1834-010319-4
*******************************

NWB file already exists for action 1834-010319-4
Spikeinterface folder already exists for action 1834-010319-4
Action 1834-010319-4 done in 0.01 s

*******************************
Processing action 1849-280219-1
*******************************

>>> Re-copying action 1849-280219-1 to new project


>>> Converting to NWB

Source data is valid!
Error processing action 1849-280219-1. Removing it from new project:
Error:
Only single recordings are currently supported


*******************************
Processing action 1833-120619-2
*******************************

NWB file already exists for action 1833-120619-2
Spikeinterface folder already exists for action 1833-120619-2
Action 1833-120619-2 done in 0.03 s

*******************************
Processing action 1833-200619-3
*******************************

NWB file already exists for action 1833-200619-3
Spikeinterface folder already exists for action 1833-200619-3
Action 1833-200619-3 done in 0.03 s

*******************************
Processing action 1839-200619-2
*******************************

NWB file already exists for action 1839-200619-2
Spikeinterface folder already exists for action 1839-200619-2
Action 1839-200619-2 done in 0.05 s

*******************************
Processing action 1833-200619-4
*******************************

NWB file already exists for action 1833-200619-4
Spikeinterface folder already exists for action 1833-200619-4
Action 1833-200619-4 done in 0.02 s

*******************************
Processing action 1833-290519-4
*******************************

>>> Re-copying action 1833-290519-4 to new project


>>> Converting to NWB

Source data is valid!
Attaching probe
Running conversion to NWB
Metadata is valid!
conversion_options is valid!
NWB file saved at /projects/ec109/Mikkel/septum-mec-new/actions/1833-290519-4/data/main.nwb!
Error processing action 1833-290519-4. Removing it from new project:
Error:



*******************************
Processing action 1849-270219-1
*******************************

NWB file already exists for action 1849-270219-1
Spikeinterface folder already exists for action 1849-270219-1
Action 1849-270219-1 done in 0.06 s

*******************************
Processing action 1834-120319-3
*******************************

NWB file already exists for action 1834-120319-3
Spikeinterface folder already exists for action 1834-120319-3
Action 1834-120319-3 done in 0.02 s

*******************************
Processing action 1849-060319-2
*******************************

NWB file already exists for action 1849-060319-2
Spikeinterface folder already exists for action 1849-060319-2
Action 1849-060319-2 done in 0.01 s

*******************************
Processing action 1833-260619-2
*******************************

NWB file already exists for action 1833-260619-2
Spikeinterface folder already exists for action 1833-260619-2
Action 1833-260619-2 done in 0.02 s

*******************************
Processing action 1834-110319-5
*******************************

NWB file already exists for action 1834-110319-5
Spikeinterface folder already exists for action 1834-110319-5
Action 1834-110319-5 done in 0.02 s

*******************************
Processing action 1849-060319-3
*******************************

NWB file already exists for action 1849-060319-3
Spikeinterface folder already exists for action 1849-060319-3
Action 1849-060319-3 done in 0.01 s

*******************************
Processing action 1833-060619-2
*******************************

NWB file already exists for action 1833-060619-2
Spikeinterface folder already exists for action 1833-060619-2
Action 1833-060619-2 done in 0.01 s

*******************************
Processing action 1833-260619-3
*******************************

NWB file already exists for action 1833-260619-3
Spikeinterface folder already exists for action 1833-260619-3
Action 1833-260619-3 done in 0.02 s

*******************************
Processing action 1834-110319-2
*******************************

NWB file already exists for action 1834-110319-2
Spikeinterface folder already exists for action 1834-110319-2
Action 1834-110319-2 done in 0.01 s

*******************************
Processing action 1834-010319-3
*******************************

NWB file already exists for action 1834-010319-3
Spikeinterface folder already exists for action 1834-010319-3
Action 1834-010319-3 done in 0.03 s

*******************************
Processing action 1834-110319-3
*******************************

NWB file already exists for action 1834-110319-3
Spikeinterface folder already exists for action 1834-110319-3
Action 1834-110319-3 done in 0.01 s

*******************************
Processing action 1839-120619-3
*******************************

NWB file already exists for action 1839-120619-3
Spikeinterface folder already exists for action 1839-120619-3
Action 1839-120619-3 done in 0.01 s

Total time: 970.62 s

*********
ALL DONE!
*********

Successful: 82

Actions failed: 10
        1833-060619-1
        1849-220319-3
        1833-120619-3
        1833-290519-2
        1834-220319-3
        1833-050619-1
        1849-150319-2
        1833-020719-2
        1849-280219-1
        1833-290519-4
```

**Comment by alejoe91** [comment]
Thanks @lepmik 

The first error is very easy to solve, pushing a fix.
For the second error, it means you have multiple experiments in the Open Ephys folder. Is this something you normally do?
The code assumes that you have a single experiment+recording per session, which corresponds to an NWB file.

What do you suggest to do in that case?

**Comment by alejoe91** [comment]
First issue should be fixed!

**Comment by lepmik** [comment]
The block stuff seems to be a fluke, I will just delete the second block

**Comment by lepmik** [comment]
what does Only single recordings are currently supported mean?

**Comment by alejoe91** [comment]
That each open ephys folder should have 1 experiment and 1 recording. In principle, you can have multiple recordings by playing/pausing several times. But in your case each recording is a separate action. Makes sense?

**Comment by lepmik** [comment]
makes sense, however, the excess spikes is still not working

**Comment by alejoe91** [comment]
Will double check tomorrow

**Comment by alejoe91** [comment]
Fixed now ;)

![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/17097257/376bc2b8-0fa0-480a-bd78-4e76270b0eb7)
